services:
  db:
    image: postgres:16
    container_name: postgres-db
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    ports:
      - "5000:5000"

    depends_on:
      - db

    env_file:
      - .env
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana

  jenkins:
    build: ./jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
volumes:
  postgres_data:
  grafana_data:
  jenkins_home:
