services:
  db:
    image: postgres:16
    container_name: postgres-db
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: employee-app

    ports:
      - "5000:5000"

    depends_on:
      - db

    env_file:
      - .env
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app-network:
volumes:
  postgres_data:
  grafana_data:
